apiVersion: v1
kind: Service
metadata:
  name: lldap-service
  namespace: ldap
spec:
  type: NodePort
  selector:
    app: lldap
  ports:
    - name: http
      port: 3890
      targetPort: 3890
      nodePort: 3890
    - name: http
      port: 17170
      targetPort: 17170
      nodePort: 17170


