apiVersion: v1
kind: Service
metadata:
  name: lldap-service
  namespace: ldap
spec:
  type: NodePort
  selector:
    app: lldap
  ports:
    - name: "3890"
      port: 3890
      targetPort: 3890
      nodePort: 30890
    - name: "17170"
      port: 17170
      targetPort: 17170
      nodePort: 32170


