apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-openldap.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-openldap.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: openldap
    spec:
      containers:
        - env:
            - name: LDAP_ADMIN_PASSWORD
              value: admin
            - name: LDAP_CONFIG_PASSWORD
              value: config
            - name: LDAP_DOMAIN
              value: example.org
            - name: LDAP_ORGANISATION
              value: example-org
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "true"
            - name: LDAP_RFC2307BIS_SCHEMA
              value: "true"
            - name: LDAP_TLS_VERIFY_CLIENT
              value: never
          image: osixia/openldap:1.5.0
          name: openldap
          volumeMounts:
            - mountPath: /var/lib/ldap
              name: openldap-claim0
            - mountPath: /etc/ldap/slapd.d
              name: openldap-claim1
      restartPolicy: Always
      volumes:
        - name: openldap-claim0
          persistentVolumeClaim:
            claimName: openldap-claim0
        - name: openldap-claim1
          persistentVolumeClaim:
            claimName: openldap-claim1
