apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-openldap.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: openldap-ui
  name: openldap-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-openldap.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: openldap-ui
    spec:
      containers:
        - env:
            - name: LDAP_ADMINS_GROUP
              value: admins
            - name: LDAP_ADMIN_BIND_DN
              value: cn=admin,dc=example,dc=org
            - name: LDAP_ADMIN_BIND_PWD
              value: admin
            - name: LDAP_BASE_DN
              value: dc=example,dc=org
            - name: LDAP_IGNORE_CERT_ERRORS
              value: "true"
            - name: LDAP_REQUIRE_STARTTLS
              value: "FALSE"
            - name: LDAP_URI
              value: ldap://openldap
            - name: NO_HTTPS
              value: "TRUE"
            - name: PASSWORD_HASH
              value: SSHA
            - name: SERVER_HOSTNAME
              value: localhost:18080
          image: wheelybird/ldap-user-manager:v1.5
          name: openldap-ui
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
