apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-openldap.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: openldap-ui
  name: openldap-ui
spec:
  ports:
    - name: "18080"
      port: 18080
      targetPort: 80
  selector:
    io.kompose.service: openldap-ui
